blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/kolirt/laravel-settings?tab=readme-ov-file#laravel-settings
    about: Check the documentation for guides and examples.